add_library(db_factory db_factory.cc)
add_library(basic_db basic_db.h)
add_library(wot_db wotdb.cc)
add_library(btree btree_db.cc)
add_library(buffer_tree_db buffer_tree_db.cc)

include_directories(~/software/leveldb/)
find_library(LEVELDB_LIB leveldb PATHS ~/software/leveldb/build)
find_library(SNAPPY_LIB snappy PATHS ~/software/snappy/build)
add_library(level level_db.cc)

target_link_libraries(btree WotAdapt)
target_link_libraries(wot_db WotAdapt)
target_link_libraries(level ${LEVELDB_LIB} ${SNAPPY_LIB})
target_link_libraries(buffer_tree_db WotAdapt)
set_target_properties(basic_db PROPERTIES LINKER_LANGUAGE CXX)
set_target_properties(wot_db PROPERTIES LINKER_LANGUAGE CXX)
set_target_properties(btree PROPERTIES LINKER_LANGUAGE CXX)
set_target_properties(buffer_tree_db PROPERTIES LINKER_LANGUAGE CXX)
target_link_libraries(db_factory basic_db wot_db btree level buffer_tree_db)
